remote_theme: pages-themes/minimal@v0.2.0
title: Ashish Rawat
logo: /assets/img/profile_image.jpg
#description: text below image
show_downloads: true
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
